### PR TITLE
Implement an option to compile with an increased (changed) maximum

### PR DESCRIPTION
**Pull request by mschuene7**
field length (other than the 1024).

After ./configure, set parameter FBUF in the Makefile.

### CODE REVIEW

**Comment by n-t-roff** [comment]
There is an off-topic change in the patch which forces use of bison. Is it necessary in the context of this issue?

**Comment by mschuene7** [comment]
> There is an off-topic change in the patch which forces use of bison. Is it necessary in the context of this issue?

I just do not have yacc installed ... so I get an error ... therefore switched to bison.

**Comment by n-t-roff** [comment]
There would need to be some kind of auto configure. It would not be hard to add it to the configure script. But this is unrelated to the actual issue and cannot be part of the patch. Also there are systems which don't use GNU software but e.g. `byacc` instead.
I suggest to remove this change from the patch and prepare an additional pull-request with a change to the `configure` script which test for `yacc`, `byacc` and `bison` and then sets `YACC`. (Unfortunately I had forget to do that in the past.)

The other changes look good to me but I have not tested them.

**Comment by mschuene7** [comment]
.

**Comment by n-t-roff** [comment]
Now you you have closed the whole pull request. As said I had not tested it but if it works I would not have an issue with committing it (@dtkerns do you have objections?).

**Comment by dtkerns** [comment]
none

**Comment by mschuene7** [comment]
re-open

**Pull request merged**
